"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "Users",
      [
        {
          firstName: "Jordan",
          lastName: "Smith",
          email: "jordan@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Chelsea",
          lastName: "Crowson",
          email: "chelsea.crowson@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jeremy",
          lastName: "Roussel",
          email: "jeremy.roussel@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Derrick",
          lastName: "White",
          email: "derrick.white@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jason",
          lastName: "Zust",
          email: "jason.zust@umbrage.com",
          craft: "Product",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jerome",
          lastName: "Ferreira",
          email: "jerome.ferreira@umbrage.com",
          craft: "Product",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Josh",
          lastName: "Luedicke",
          email: "josh@umbrage.com",
          craft: "Product",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Kendal",
          lastName: "Jefferies",
          email: "kendal.jefferies@umbrage.com",
          craft: "Product",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Meagan",
          lastName: "Rowell",
          email: "meagan.rowell@umbrage.com",
          craft: "Product",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Roger",
          lastName: "Sun",
          email: "roger.sun@umbrage.com",
          craft: "Product",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Will",
          lastName: "Carey",
          email: "will.carey@umbrage.com",
          craft: "Product",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Benjamin",
          lastName: "Bass",
          email: "benjamin.bass@umbrage.com",
          craft: "Product",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Barrette",
          lastName: "Banner",
          email: "barrette.banner@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Kevin",
          lastName: "Moore",
          email: "kevin.moore@umbrage.com",
          craft: "QA",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Anas",
          lastName: "Ghadieh",
          email: "anas.ghadieh@umbrage.com",
          craft: "QA",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Sandy",
          lastName: "Pham",
          email: "sandy.pham@umbrage.com",
          craft: "Design",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Piero",
          lastName: "Rojas",
          email: "piero.rojas@umbrage.com",
          craft: "Design",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Martin",
          lastName: "Pepper",
          email: "martin.pepper@umbrage.com",
          craft: "Design",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Joshua",
          lastName: "Bird",
          email: "jbird@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jose",
          lastName: "Mendoza",
          email: "jose.mendoza@umbrage.com",
          craft: "Design",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ben",
          lastName: "MeCraw",
          email: "ben.mccraw@umbrage.com",
          craft: "Design",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Zach",
          lastName: "Little",
          email: "zach.little@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Tyler",
          lastName: "Neustaedter",
          email: "tyler.neustaedter@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Rocky",
          lastName: "Chiang",
          email: "rocky.chiang@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Michael",
          lastName: "Evans",
          email: "michael.evans@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "McRae",
          lastName: "Peavy",
          email: "mcrae.peavy@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Matthew",
          lastName: "Spilman",
          email: "matthew.spilman@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Matthew",
          lastName: "Groff",
          email: "matt@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Dave",
          lastName: "Shah",
          email: "dave.shah@umbrage.com",
          craft: "Product",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jesus",
          lastName: "Mendoza",
          email: "jose.mendoza@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ahmed",
          lastName: "Aly",
          email: "ahmed@umbrage.com",
          craft: "Engineering",
          rate: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("Users", null, {});
  },
};
